-- ===============================
-- RESET (WAJIB BIAR BERSIH)
-- ===============================
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS users;

-- ===============================
-- USERS
-- ===============================
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password TEXT NOT NULL,
  phone VARCHAR(15),
  address TEXT,
  "profilePhoto" TEXT,
  role VARCHAR(10) DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ===============================
-- PRODUCTS (GERABAH)
-- ===============================
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  material VARCHAR(100),
  size VARCHAR(100),
  color VARCHAR(100),
  price NUMERIC(10,2) NOT NULL,
  category VARCHAR(100),
  image TEXT,
  rating NUMERIC(3,1) DEFAULT 0,
  reviews INT DEFAULT 0,
  discount INT DEFAULT 0,
  stock INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ===============================
-- ORDERS
-- ===============================
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number VARCHAR(20) UNIQUE NOT NULL,
  user_id BIGINT NOT NULL,
  items JSON NOT NULL,
  total NUMERIC(10,2) NOT NULL,
  status VARCHAR(50) DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ===============================
-- INSERT ADMIN
-- ===============================
INSERT INTO users (username, email, password, phone, address, role)
VALUES (
  'admin',
  'admin@tokogerabah.com',
  '$2a$10$d8K07IChvhqzTk8vuP.kPuQOfLh6ubVLI63MpdMdKCIwRgnWQ8LdS',
  '08123456789',
  'Jl. Gerabah No. 1, Yogyakarta',
  'admin'
);

-- ===============================
-- INSERT PRODUK
-- ===============================
INSERT INTO products 
(name, description, material, size, color, price, category, rating, reviews, discount, stock)
VALUES
('Vas Keramik Unik', 'Vas keramik handmade desain tradisional', 'Keramik', '30x25 cm', 'Merah Maroon', 150000, 'Dekorasi', 4.5, 12, 10, 15),
('Piring Gerabah Batik', 'Piring motif batik khas Jawa', 'Tanah Liat', '25 cm', 'Coklat Natural', 85000, 'Peralatan Makan', 4.2, 8, 0, 20),
('Kendi Tradisional', 'Kendi klasik untuk air minum', 'Tanah Liat', '35x20 cm', 'Merah', 120000, 'Dekorasi', 4.8, 18, 15, 10),
('Mangkuk Gerabah Besar', 'Mangkuk besar untuk saji makanan', 'Gerabah', '30 cm', 'Biru Celadon', 95000, 'Peralatan Makan', 4.3, 10, 5, 25),
('Guci Penyimpan Beras', 'Guci tradisional penyimpan beras', 'Tanah Liat', '50 cm', 'Coklat', 250000, 'Penyimpanan', 4.6, 14, 20, 8),
('Pot Tanaman Keramik', 'Pot bunga dengan drainase', 'Keramik', '20x20 cm', 'Kuning Mustard', 65000, 'Dekorasi', 4.1, 6, 0, 30),
('Ceret Teh Gerabah', 'Ceret teh tradisional berkualitas', 'Gerabah', '15 cm', 'Hitam', 105000, 'Peralatan Minum', 4.4, 11, 10, 16),
('Hiasan Dinding Gerabah', 'Hiasan dinding motif abstrak', 'Gerabah', '40x30 cm', 'Beige', 175000, 'Dekorasi', 4.7, 16, 15, 12);
